# Generated by Django 2.2.7 on 2019-11-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.TextField()),
                ('year', models.IntegerField()),
                ('title', models.TextField()),
                ('journal', models.CharField(max_length=200)),
                ('volume', models.IntegerField()),
                ('initialPage', models.IntegerField()),
            ],
        ),
    ]
