# Generated by Django 2.2.7 on 2019-11-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_publications'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='publication_type',
            field=models.CharField(choices=[('Paper', 'Paper'), ('Review', 'Review'), ('Chapter', 'Chapter'), ('Proceeding', 'Proceeding')], default='Paper', max_length=20),
        ),
    ]
