# Generated by Django 2.2.7 on 2019-11-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_publications_publication_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('PI', 'PI'), ('Postdoc', 'Postdoc'), ('PhD', 'PhD'), ('Technician', 'Technician'), ('MSc', 'MSc'), ('Guest_PhD', 'Guest_PhD'), ('Guest_Student', 'Guest_Student')], default='PhD', max_length=20)),
                ('initial_year', models.IntegerField()),
                ('final_year', models.IntegerField()),
            ],
        ),
    ]
