# Generated by Django 2.2.7 on 2019-11-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PI_name', models.CharField(default='PI Name', max_length=200)),
                ('PI_position', models.CharField(default='PI Position', max_length=200)),
                ('group_name', models.CharField(default='e.g., Soft Matter', max_length=200)),
                ('group_def', models.CharField(default='e.g., Lab, Group, etc.', max_length=200)),
                ('group_short_description', models.CharField(default='e.g., Soft Matter at Interfaces', max_length=200)),
                ('group_long_description', models.TextField(default='We do research on...')),
            ],
        ),
        migrations.AlterModelOptions(
            name='publications',
            options={'verbose_name_plural': 'Publications'},
        ),
    ]
