# Generated by Django 2.2.7 on 2019-11-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20191127_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserachField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('main_image', models.ImageField(blank=True, upload_to='research_field_images')),
            ],
        ),
    ]
