# Generated by Django 2.2.7 on 2019-11-29 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_reserachfield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReserachField',
            new_name='ResearchField',
        ),
    ]
