# Generated by Django 2.2.7 on 2019-12-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20191129_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='member',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='members_images'),
        ),
    ]
