# Generated by Django 3.0.2 on 2020-04-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20191201_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bio',
            field=models.TextField(blank=True, default='Coming Soon'),
        ),
    ]
