# Generated by Django 3.0.2 on 2020-04-24 15:22

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200424_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchfield',
            name='long_html_description',
            field=tinymce.models.HTMLField(blank=True, default='html default'),
        ),
        migrations.AlterField(
            model_name='researchfield',
            name='long_description',
            field=models.TextField(),
        ),
    ]
