# Generated by Django 3.0.2 on 2020-04-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20200424_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchfield',
            name='long_html_description',
        ),
        migrations.AddField(
            model_name='researchfield',
            name='secondary_image',
            field=models.ImageField(blank=True, upload_to='research_field_images'),
        ),
    ]
